# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.2'
    - run: make build
# Run tests here

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.2'
        
    - name: Build
      run: make build
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "linux_x64"
        path: bin/pod-interpreter
        
  pages:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.2'
        
    - name: Build
      run: make build-wasm

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: "github-pages"
          path: bin/web/

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: pages
    permissions:
      pages: write 
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
          
